name: Run FastAPI Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn faster-whisper pydub psutil pyngrok nest_asyncio tenacity torch deep-translator requests

    - name: Run FastAPI server
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        python transcribe_whisper.ipynb
